;;; treemacs-material-icons.el --- material icons for treemacs -*- lexical-binding: t; -*-
;;
;; Copyright (C) 2023 Noam Taifeld
;;
;; Author: Noam Taifeld <ikapodev@gmail.com>
;; Maintainer: Noam Taifeld <ikapodev@gmail.com>
;; Version: 0.0.1
;; Homepage: https://github.com/ikapo/treemacs-material-icons
;; Package-Requires: ((emacs "26.1") (treemacs "2.5"))
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;;
;;; Commentary:
;; Material icons for treemacs
;;; Code:
(require 'treemacs)
(require 'find-func)

(with-eval-after-load 'treemacs
  (treemacs-create-theme "material-icons"
    :icon-directory (treemacs-join-path (file-name-directory (find-library-name "treemacs-material-icons")) "material-icons")
    :config
    (progn
    (treemacs-create-icon :file "folder-root-open.svg"   :extensions (root-open))
    (treemacs-create-icon :file "folder-root.svg"        :extensions (root-closed))
    (treemacs-create-icon :file "folder-open.svg"        :extensions (dir-open))
    (treemacs-create-icon :file "folder.svg"             :extensions (dir-closed))
    (treemacs-create-icon :file "file.svg"               :extensions (fallback))
    (treemacs-create-icon :file "emacs.svg"              :extensions ("el" "elc"))
    (treemacs-create-icon :file "html.svg"               :extensions ("htm" "xhtml" "html_vm" "asp"))
    (treemacs-create-icon :file "pug.svg"                :extensions ("jade" "pug" ".pug-lintrc" ".pug-lintrc.js" ".pug-lintrc.json"))
    (treemacs-create-icon :file "markdown.svg"           :extensions ("md" "markdown" "rst"))
    (treemacs-create-icon :file "blink.svg"              :extensions ("blink"))
    (treemacs-create-icon :file "css.svg"                :extensions ("css"))
    (treemacs-create-icon :file "sass.svg"               :extensions ("scss" "sass"))
    (treemacs-create-icon :file "less.svg"               :extensions ("less"))
    (treemacs-create-icon :file "json.svg"               :extensions ("json" "jsonc" "tsbuildinfo" "json5" "jsonl" "ndjson" ".jscsrc" ".jshintrc" "composer.lock" ".jsbeautifyrc" ".esformatter" "cdp.pid" ".lintstagedrc"))
    (treemacs-create-icon :file "jinja.svg"              :extensions ("jinja" "jinja2" "j2" "jinja-html"))
    (treemacs-create-icon :file "proto.svg"              :extensions ("proto"))
    (treemacs-create-icon :file "playwright.svg"         :extensions ("playwright.config.js" "playwright.config.mjs" "playwright.config.ts" "playwright-ct.config.js" "playwright-ct.config.mjs" "playwright-ct.config.ts"))
    (treemacs-create-icon :file "sublime.svg"            :extensions ("sublime-project" "sublime-workspace"))
    (treemacs-create-icon :file "twine.svg"              :extensions ("tw" "twee"))
    (treemacs-create-icon :file "yaml.svg"               :extensions ("yml" "yaml" "yml.dist" "yaml.dist" "YAML-tmLanguage"))
    (treemacs-create-icon :file "xml.svg"                :extensions ("xml" "plist" "xsd" "dtd" "xsl" "xslt" "resx" "iml" "xquery" "tmLanguage" "manifest" "project" "xml.dist" "xml.dist.sample" "dmn" "jrxml" ".htaccess"))
    (treemacs-create-icon :file "image.svg"              :extensions ("png" "jpeg" "jpg" "gif" "ico" "tif" "tiff" "psd" "psb" "ami" "apx" "avif" "bmp" "bpg" "brk" "cur" "dds" "dng" "exr" "fpx" "gbr" "img" "jbig2" "jb2" "jng" "jxr" "pgf" "pic" "raw" "webp" "eps" "afphoto" "ase" "aseprite" "clip" "cpt" "heif" "heic" "kra" "mdp" "ora" "pdn" "reb" "sai" "tga" "xcf" "jfif" "ppm" "pbm" "pgm" "pnm" "icns"))
    (treemacs-create-icon :file "javascript.svg"         :extensions ("esx" "mjs" "js"))
    (treemacs-create-icon :file "react.svg"              :extensions ("jsx"))
    (treemacs-create-icon :file "react_ts.svg"           :extensions ("tsx"))
    (treemacs-create-icon :file "routing.svg"            :extensions ("routing.ts" "routing.tsx" "routing.js" "routing.jsx" "routes.ts" "routes.tsx" "routes.js" "routes.jsx" "router.js" "router.jsx" "router.ts" "router.tsx" "routes.js" "routes.jsx" "routes.ts" "routes.tsx"))
    (treemacs-create-icon :file "redux-action.svg"       :extensions ("action.js" "actions.js" "action.ts" "actions.ts" "action.js" "actions.js" "action.ts" "actions.ts"))
    (treemacs-create-icon :file "redux-reducer.svg"      :extensions ("reducer.js" "reducers.js" "reducer.ts" "reducers.ts" "reducer.js" "reducers.js" "reducer.ts" "reducers.ts"))
    (treemacs-create-icon :file "redux-selector.svg"     :extensions ("selector.js" "selectors.js" "selector.ts" "selectors.ts" "selector.js" "selectors.js" "selector.ts" "selectors.ts"))
    (treemacs-create-icon :file "redux-store.svg"        :extensions ("store.js" "store.ts" "store.js" "store.ts"))
    (treemacs-create-icon :file "settings.svg"           :extensions ("ini" "dlc" "dll" "config" "conf" "properties" "prop" "settings" "option" "props" "toml" "prefs" "sln.dotsettings" "sln.dotsettings.user" "cfg" ".jshintignore" ".buildignore" ".mrconfig" ".yardopts" "manifest.mf" ".clang-format" ".clang-tidy"))
    (treemacs-create-icon :file "org.svg"                :extensions ("org"))
    (treemacs-create-icon :file "typescript-def.svg"     :extensions ("d.ts" "d.cts" "d.mts" "ts"))
    (treemacs-create-icon :file "markojs.svg"            :extensions ("marko"))
    (treemacs-create-icon :file "astro.svg"              :extensions ("astro" "astro.config.js" "astro.config.mjs" "astro.config.cjs" "astro.config.ts" "astro.config.cts" "astro.config.mts"))
    (treemacs-create-icon :file "pdf.svg"                :extensions ("pdf"))
    (treemacs-create-icon :file "table.svg"              :extensions ("xlsx" "xlsm" "xls" "csv" "tsv" "psv" "ods"))
    (treemacs-create-icon :file "vscode.svg"             :extensions ("vscodeignore" "vsixmanifest" "vsix" "code-workplace" "code-workspace" "code-profile" "code-snippets"))
    (treemacs-create-icon :file "visualstudio.svg"       :extensions ("csproj" "ruleset" "sln" "suo" "vb" "vbs" "vcxitems" "vcxitems.filters" "vcxproj" "vcxproj.filters"))
    (treemacs-create-icon :file "database.svg"           :extensions ("pdb" "sql" "pks" "pkb" "accdb" "mdb" "sqlite" "sqlite3" "pgsql" "postgres" "psql" "db" "db3"))
    (treemacs-create-icon :file "kusto.svg"              :extensions ("kql"))
    (treemacs-create-icon :file "csharp.svg"             :extensions ("cs" "csx"))
    (treemacs-create-icon :file "qsharp.svg"             :extensions ("qs"))
    (treemacs-create-icon :file "zip.svg"                :extensions ("zip" "tar" "gz" "xz" "lzma" "lz4" "br" "bz2" "bzip2" "gzip" "brotli" "7z" "rar" "tz" "txz" "tgz"))
    (treemacs-create-icon :file "vala.svg"               :extensions ("vala"))
    (treemacs-create-icon :file "zig.svg"                :extensions ("zig"))
    (treemacs-create-icon :file "exe.svg"                :extensions ("exe" "msi"))
    (treemacs-create-icon :file "hex.svg"                :extensions ("dat" "bin" "hex"))
    (treemacs-create-icon :file "java.svg"               :extensions ("java" "jsp"))
    (treemacs-create-icon :file "jar.svg"                :extensions ("jar"))
    (treemacs-create-icon :file "javaclass.svg"          :extensions ("class"))
    (treemacs-create-icon :file "c.svg"                  :extensions ("c" "i" "mi"))
    (treemacs-create-icon :file "h.svg"                  :extensions ("h"))
    (treemacs-create-icon :file "cpp.svg"                :extensions ("cc" "cpp" "cxx" "c++" "cp" "mii" "ii"))
    (treemacs-create-icon :file "hpp.svg"                :extensions ("hh" "hpp" "hxx" "h++" "hp" "tcc" "inl"))
    (treemacs-create-icon :file "objective-c.svg"        :extensions ("m"))
    (treemacs-create-icon :file "objective-cpp.svg"      :extensions ("mm"))
    (treemacs-create-icon :file "go.svg"                 :extensions ("go"))
    (treemacs-create-icon :file "go-mod.svg"             :extensions ("go.mod" "go.sum" "go.work" "go.work.sum"))
    (treemacs-create-icon :file "python.svg"             :extensions ("py"))
    (treemacs-create-icon :file "python-misc.svg"        :extensions ("pyc" "whl" "requirements.txt" "pipfile" ".python-version" "manifest.in" "pylintrc" ".pylintrc" "pyproject.toml"))
    (treemacs-create-icon :file "url.svg"                :extensions ("url"))
    (treemacs-create-icon :file "console.svg"            :extensions ("sh" "ksh" "csh" "tcsh" "zsh" "bash" "bat" "cmd" "awk" "fish" "exp" "nu" "commit-msg" "pre-commit" "pre-push" "post-merge"))
    (treemacs-create-icon :file "powershell.svg"         :extensions ("ps1" "psm1" "psd1" "ps1xml" "psc1" "pssc"))
    (treemacs-create-icon :file "gradle.svg"             :extensions ("gradle" "gradle.properties" "gradlew" "gradle-wrapper.properties"))
    (treemacs-create-icon :file "word.svg"               :extensions ("doc" "docx" "rtf" "odt"))
    (treemacs-create-icon :file "certificate.svg"        :extensions ("cer" "cert" "crt" "copying" "copying.md" "copying.rst" "copying.txt" "copyright" "copyright.md" "copyright.rst" "copyright.txt" "license" "license-agpl" "license-apache" "license-bsd" "license-mit" "license-gpl" "license-lgpl" "license.md" "license.rst" "license.txt" "licence" "licence-agpl" "licence-apache" "licence-bsd" "licence-mit" "licence-gpl" "licence-lgpl" "licence.md" "licence.rst" "licence.txt"))
    (treemacs-create-icon :file "key.svg"                :extensions ("pub" "key" "pem" "asc" "gpg" "passwd" ".htpasswd"))
    (treemacs-create-icon :file "font.svg"               :extensions ("woff" "woff2" "ttf" "eot" "suit" "otf" "bmap" "fnt" "odttf" "ttc" "font" "fonts" "sui" "ntf" "mrf"))
    (treemacs-create-icon :file "lib.svg"                :extensions ("lib" "bib"))
    (treemacs-create-icon :file "ruby.svg"               :extensions ("rb" "erb"))
    (treemacs-create-icon :file "gemfile.svg"            :extensions ("gemfile"))
    (treemacs-create-icon :file "rubocop.svg"            :extensions (".rubocop.yml" ".rubocop-todo.yml" ".rubocop_todo.yml"))
    (treemacs-create-icon :file "fsharp.svg"             :extensions ("fs" "fsx" "fsi" "fsproj"))
    (treemacs-create-icon :file "swift.svg"              :extensions ("swift"))
    (treemacs-create-icon :file "arduino.svg"            :extensions ("ino"))
    (treemacs-create-icon :file "docker.svg"             :extensions ("dockerignore" "dockerfile" "docker-compose.yml" "docker-compose.yaml" "dockerfile" "dockerfile.prod" "dockerfile.production" "dockerfile.alpha" "dockerfile.beta" "dockerfile.stage" "dockerfile.staging" "dockerfile.dev" "dockerfile.development" "dockerfile.local" "dockerfile.test" "dockerfile.testing" "dockerfile.ci" "dockerfile.web" "dockerfile.worker" "docker-compose.yml" "docker-compose.override.yml" "docker-compose.prod.yml" "docker-compose.production.yml" "docker-compose.alpha.yml" "docker-compose.beta.yml" "docker-compose.stage.yml" "docker-compose.staging.yml" "docker-compose.dev.yml" "docker-compose.development.yml" "docker-compose.local.yml" "docker-compose.test.yml" "docker-compose.testing.yml" "docker-compose.ci.yml" "docker-compose.web.yml" "docker-compose.worker.yml" "docker-compose.yaml" "docker-compose.override.yaml" "docker-compose.prod.yaml" "docker-compose.production.yaml" "docker-compose.alpha.yaml" "docker-compose.beta.yaml" "docker-compose.stage.yaml" "docker-compose.staging.yaml" "docker-compose.dev.yaml" "docker-compose.development.yaml" "docker-compose.local.yaml" "docker-compose.test.yaml" "docker-compose.testing.yaml" "docker-compose.ci.yaml" "docker-compose.web.yaml" "docker-compose.worker.yaml" "compose.yaml" "compose.yml"))
    (treemacs-create-icon :file "tex.svg"                :extensions ("tex" "sty" "dtx" "ltx"))
    (treemacs-create-icon :file "powerpoint.svg"         :extensions ("pptx" "ppt" "pptm" "potx" "potm" "ppsx" "ppsm" "pps" "ppam" "ppa" "odp"))
    (treemacs-create-icon :file "video.svg"              :extensions ("webm" "mkv" "flv" "vob" "ogv" "ogg" "gifv" "avi" "mov" "qt" "wmv" "yuv" "rm" "rmvb" "mp4" "m4v" "mpg" "mp2" "mpeg" "mpe" "mpv" "m2v"))
    (treemacs-create-icon :file "virtual.svg"            :extensions ("vdi" "vbox" "vbox-prev"))
    (treemacs-create-icon :file "email.svg"              :extensions ("ics" ".mailmap"))
    (treemacs-create-icon :file "audio.svg"              :extensions ("mp3" "flac" "m4a" "wma" "aiff" "wav"))
    (treemacs-create-icon :file "coffee.svg"             :extensions ("coffee" "cson" "iced"))
    (treemacs-create-icon :file "document.svg"           :extensions ("txt"))
    (treemacs-create-icon :file "graphql.svg"            :extensions ("graphql" "gql" ".graphqlconfig" ".graphqlrc" ".graphqlrc.json" ".graphqlrc.js" ".graphqlrc.cjs" ".graphqlrc.ts" ".graphqlrc.toml" ".graphqlrc.yaml" ".graphqlrc.yml" "graphql.config.json" "graphql.config.js" "graphql.config.cjs" "graphql.config.ts" "graphql.config.toml" "graphql.config.yaml" "graphql.config.yml"))
    (treemacs-create-icon :file "rust.svg"               :extensions ("rs" "ron"))
    (treemacs-create-icon :file "raml.svg"               :extensions ("raml"))
    (treemacs-create-icon :file "xaml.svg"               :extensions ("xaml"))
    (treemacs-create-icon :file "haskell.svg"            :extensions ("hs"))
    (treemacs-create-icon :file "kotlin.svg"             :extensions ("kt" "kts"))
    (treemacs-create-icon :file "otne.svg"               :extensions ("otne"))
    (treemacs-create-icon :file "git.svg"                :extensions ("patch" ".git" ".gitignore" ".gitignore-global" ".gitignore_global" ".gitattributes" ".gitattributes-global" ".gitattributes_global" ".gitconfig" ".gitmodules" ".gitkeep" ".gitinclude" ".git-blame-ignore" ".git-blame-ignore-revs" ".git-for-windows-updater" "git-history"))
    (treemacs-create-icon :file "lua.svg"                :extensions ("lua" ".luacheckrc"))
    (treemacs-create-icon :file "clojure.svg"            :extensions ("clj" "cljs" "cljc"))
    (treemacs-create-icon :file "groovy.svg"             :extensions ("groovy"))
    (treemacs-create-icon :file "r.svg"                  :extensions ("r" "rmd" ".Rhistory"))
    (treemacs-create-icon :file "dart.svg"               :extensions ("dart" ".pubignore"))
    (treemacs-create-icon :file "dart_generated.svg"     :extensions ("freezed.dart" "g.dart"))
    (treemacs-create-icon :file "actionscript.svg"       :extensions ("as"))
    (treemacs-create-icon :file "mxml.svg"               :extensions ("mxml"))
    (treemacs-create-icon :file "autohotkey.svg"         :extensions ("ahk"))
    (treemacs-create-icon :file "flash.svg"              :extensions ("swf"))
    (treemacs-create-icon :file "swc.svg"                :extensions ("swc"))
    (treemacs-create-icon :file "cmake.svg"              :extensions ("cmake" "cmakelists.txt" "cmakecache.txt"))
    (treemacs-create-icon :file "assembly.svg"           :extensions ("asm" "a51" "inc" "nasm" "s" "ms" "agc" "ags" "aea" "argus" "mitigus" "binsource"))
    (treemacs-create-icon :file "vue.svg"                :extensions ("vue"))
    (treemacs-create-icon :file "vue-config.svg"         :extensions ("vue.config.js" "vue.config.ts" "vetur.config.js" "vetur.config.ts" "volar.config.js"))
    (treemacs-create-icon :file "vuex-store.svg"         :extensions ("store.js" "store.ts" "store.js" "store.ts"))
    (treemacs-create-icon :file "nuxt.svg"               :extensions ("nuxt.config.js" "nuxt.config.ts" ".nuxtignore"))
    (treemacs-create-icon :file "ocaml.svg"              :extensions ("ml" "mli" "cmx"))
    (treemacs-create-icon :file "odin.svg"               :extensions ("odin"))
    (treemacs-create-icon :file "javascript-map.svg"     :extensions ("js.map" "mjs.map" "cjs.map"))
    (treemacs-create-icon :file "css-map.svg"            :extensions ("css.map"))
    (treemacs-create-icon :file "lock.svg"               :extensions ("lock" "security.md" "security.txt" "security"))
    (treemacs-create-icon :file "handlebars.svg"         :extensions ("hbs" "mustache"))
    (treemacs-create-icon :file "perl.svg"               :extensions ("pm" "raku"))
    (treemacs-create-icon :file "haxe.svg"               :extensions ("hx"))
    (treemacs-create-icon :file "test-ts.svg"            :extensions ("spec.ts" "spec.cts" "spec.mts" "cy.ts" "e2e-spec.ts" "e2e-spec.cts" "e2e-spec.mts" "test.ts" "test.cts" "test.mts" "ts.snap" "spec-d.ts" "test-d.ts"))
    (treemacs-create-icon :file "test-jsx.svg"           :extensions ("spec.tsx" "test.tsx" "tsx.snap" "spec.jsx" "test.jsx" "jsx.snap" "cy.jsx" "cy.tsx" "spec-d.tsx" "test-d.tsx"))
    (treemacs-create-icon :file "test-js.svg"            :extensions ("spec.js" "spec.cjs" "spec.mjs" "e2e-spec.js" "e2e-spec.cjs" "e2e-spec.mjs" "test.js" "test.cjs" "test.mjs" "js.snap" "cy.js"))
    (treemacs-create-icon :file "angular.svg"            :extensions ("module.ts" "module.js" "ng-template" "angular-cli.json" ".angular-cli.json" "angular.json" "ng-package.json"))
    (treemacs-create-icon :file "angular-component.svg"  :extensions ("component.ts" "component.js"))
    (treemacs-create-icon :file "angular-guard.svg"      :extensions ("guard.ts" "guard.js"))
    (treemacs-create-icon :file "angular-service.svg"    :extensions ("service.ts" "service.js"))
    (treemacs-create-icon :file "angular-pipe.svg"       :extensions ("pipe.ts" "pipe.js" "filter.js"))
    (treemacs-create-icon :file "angular-directive.svg"  :extensions ("directive.ts" "directive.js"))
    (treemacs-create-icon :file "angular-resolver.svg"   :extensions ("resolver.ts" "resolver.js"))
    (treemacs-create-icon :file "puppet.svg"             :extensions ("pp"))
    (treemacs-create-icon :file "elixir.svg"             :extensions ("ex" "exs" "eex" "leex" "heex"))
    (treemacs-create-icon :file "livescript.svg"         :extensions ("ls"))
    (treemacs-create-icon :file "erlang.svg"             :extensions ("erl"))
    (treemacs-create-icon :file "twig.svg"               :extensions ("twig"))
    (treemacs-create-icon :file "julia.svg"              :extensions ("jl"))
    (treemacs-create-icon :file "elm.svg"                :extensions ("elm"))
    (treemacs-create-icon :file "purescript.svg"         :extensions ("pure" "purs"))
    (treemacs-create-icon :file "smarty.svg"             :extensions ("tpl"))
    (treemacs-create-icon :file "stylus.svg"             :extensions ("styl"))
    (treemacs-create-icon :file "reason.svg"             :extensions ("re" "rei"))
    (treemacs-create-icon :file "bucklescript.svg"       :extensions ("cmj"))
    (treemacs-create-icon :file "merlin.svg"             :extensions ("merlin"))
    (treemacs-create-icon :file "verilog.svg"            :extensions ("vhd" "sv" "svh"))
    (treemacs-create-icon :file "mathematica.svg"        :extensions ("nb"))
    (treemacs-create-icon :file "wolframlanguage.svg"    :extensions ("wl" "wls"))
    (treemacs-create-icon :file "nunjucks.svg"           :extensions ("njk" "nunjucks"))
    (treemacs-create-icon :file "robot.svg"              :extensions ("robot"))
    (treemacs-create-icon :file "solidity.svg"           :extensions ("sol"))
    (treemacs-create-icon :file "autoit.svg"             :extensions ("au3"))
    (treemacs-create-icon :file "haml.svg"               :extensions ("haml"))
    (treemacs-create-icon :file "yang.svg"               :extensions ("yang"))
    (treemacs-create-icon :file "mjml.svg"               :extensions ("mjml" ".mjmlconfig"))
    (treemacs-create-icon :file "vercel.svg"             :extensions ("vercel.json" ".vercelignore" "now.json" ".nowignore"))
    (treemacs-create-icon :file "verdaccio.svg"          :extensions ("verdaccio.yml"))
    (treemacs-create-icon :file "next.svg"               :extensions ("next.config.js" "next.config.mjs" "next.config.ts" "next.config.mts"))
    (treemacs-create-icon :file "remix.svg"              :extensions ("remix.config.js" "remix.config.ts"))
    (treemacs-create-icon :file "terraform.svg"          :extensions ("tf" "tf.json" "tfvars" "tfstate"))
    (treemacs-create-icon :file "laravel.svg"            :extensions ("blade.php" "inky.php" "artisan"))
    (treemacs-create-icon :file "applescript.svg"        :extensions ("applescript" "ipa"))
    (treemacs-create-icon :file "cake.svg"               :extensions ("cake"))
    (treemacs-create-icon :file "cucumber.svg"           :extensions ("feature" "features"))
    (treemacs-create-icon :file "nim.svg"                :extensions ("nim" "nimble"))
    (treemacs-create-icon :file "apiblueprint.svg"       :extensions ("apib" "apiblueprint"))
    (treemacs-create-icon :file "riot.svg"               :extensions ("riot" "tag"))
    (treemacs-create-icon :file "vfl.svg"                :extensions ("vfl" ".vfl"))
    (treemacs-create-icon :file "kl.svg"                 :extensions ("kl" ".kl"))
    (treemacs-create-icon :file "postcss.svg"            :extensions ("pcss" "sss" "postcss.config.js" "postcss.config.cjs" "postcss.config.ts" "postcss.config.cts" ".postcssrc.js" ".postcssrc.cjs" ".postcssrc.ts" ".postcssrc.cts" ".postcssrc" ".postcssrc.json" ".postcssrc.yaml" ".postcssrc.yml"))
    (treemacs-create-icon :file "posthtml.svg"           :extensions ("posthtml.config.js" ".posthtmlrc.js" ".posthtmlrc" ".posthtmlrc.json" ".posthtmlrc.yml"))
    (treemacs-create-icon :file "todo.svg"               :extensions ("todo" "todo.md" "todos.md"))
    (treemacs-create-icon :file "coldfusion.svg"         :extensions ("cfml" "cfc" "lucee" "cfm"))
    (treemacs-create-icon :file "cabal.svg"              :extensions ("cabal" "cabal.project" "cabal.project.freeze" "cabal.project.local"))
    (treemacs-create-icon :file "nix.svg"                :extensions ("nix"))
    (treemacs-create-icon :file "slim.svg"               :extensions ("slim"))
    (treemacs-create-icon :file "http.svg"               :extensions ("http" "rest" "CNAME"))
    (treemacs-create-icon :file "restql.svg"             :extensions ("rql" "restql"))
    (treemacs-create-icon :file "kivy.svg"               :extensions ("kv"))
    (treemacs-create-icon :file "graphcool.svg"          :extensions ("graphcool" "project.graphcool"))
    (treemacs-create-icon :file "sbt.svg"                :extensions ("sbt"))
    (treemacs-create-icon :file "webpack.svg"            :extensions ("webpack.js" "webpack.cjs" "webpack.mjs" "webpack.ts" "webpack.cts" "webpack.mts" "webpack.base.js" "webpack.base.cjs" "webpack.base.mjs" "webpack.base.ts" "webpack.base.cts" "webpack.base.mts" "webpack.config.js" "webpack.config.cjs" "webpack.config.mjs" "webpack.config.ts" "webpack.config.cts" "webpack.config.mts" "webpack.common.js" "webpack.common.cjs" "webpack.common.mjs" "webpack.common.ts" "webpack.common.cts" "webpack.common.mts" "webpack.config.common.js" "webpack.config.common.cjs" "webpack.config.common.mjs" "webpack.config.common.ts" "webpack.config.common.cts" "webpack.config.common.mts" "webpack.config.common.babel.js" "webpack.config.common.babel.ts" "webpack.dev.js" "webpack.dev.cjs" "webpack.dev.mjs" "webpack.dev.ts" "webpack.dev.cts" "webpack.dev.mts" "webpack.development.js" "webpack.development.cjs" "webpack.development.mjs" "webpack.development.ts" "webpack.development.cts" "webpack.development.mts" "webpack.config.dev.js" "webpack.config.dev.cjs" "webpack.config.dev.mjs" "webpack.config.dev.ts" "webpack.config.dev.cts" "webpack.config.dev.mts" "webpack.config.dev.babel.js" "webpack.config.dev.babel.ts" "webpack.mix.js" "webpack.mix.cjs" "webpack.mix.mjs" "webpack.mix.ts" "webpack.mix.cts" "webpack.mix.mts" "webpack.prod.js" "webpack.prod.cjs" "webpack.prod.mjs" "webpack.prod.ts" "webpack.prod.cts" "webpack.prod.mts" "webpack.prod.config.js" "webpack.prod.config.cjs" "webpack.prod.config.mjs" "webpack.prod.config.ts" "webpack.prod.config.cts" "webpack.prod.config.mts" "webpack.production.js" "webpack.production.cjs" "webpack.production.mjs" "webpack.production.ts" "webpack.production.cts" "webpack.production.mts" "webpack.server.js" "webpack.server.cjs" "webpack.server.mjs" "webpack.server.ts" "webpack.server.cts" "webpack.server.mts" "webpack.client.js" "webpack.client.cjs" "webpack.client.mjs" "webpack.client.ts" "webpack.client.cts" "webpack.client.mts" "webpack.config.server.js" "webpack.config.server.cjs" "webpack.config.server.mjs" "webpack.config.server.ts" "webpack.config.server.cts" "webpack.config.server.mts" "webpack.config.client.js" "webpack.config.client.cjs" "webpack.config.client.mjs" "webpack.config.client.ts" "webpack.config.client.cts" "webpack.config.client.mts" "webpack.config.production.babel.js" "webpack.config.production.babel.ts" "webpack.config.prod.babel.js" "webpack.config.prod.babel.cjs" "webpack.config.prod.babel.mjs" "webpack.config.prod.babel.ts" "webpack.config.prod.babel.cts" "webpack.config.prod.babel.mts" "webpack.config.prod.js" "webpack.config.prod.cjs" "webpack.config.prod.mjs" "webpack.config.prod.ts" "webpack.config.prod.cts" "webpack.config.prod.mts" "webpack.config.production.js" "webpack.config.production.cjs" "webpack.config.production.mjs" "webpack.config.production.ts" "webpack.config.production.cts" "webpack.config.production.mts" "webpack.config.staging.js" "webpack.config.staging.cjs" "webpack.config.staging.mjs" "webpack.config.staging.ts" "webpack.config.staging.cts" "webpack.config.staging.mts" "webpack.config.babel.js" "webpack.config.babel.ts" "webpack.config.base.babel.js" "webpack.config.base.babel.ts" "webpack.config.base.js" "webpack.config.base.cjs" "webpack.config.base.mjs" "webpack.config.base.ts" "webpack.config.base.cts" "webpack.config.base.mts" "webpack.config.staging.babel.js" "webpack.config.staging.babel.ts" "webpack.config.coffee" "webpack.config.test.js" "webpack.config.test.cjs" "webpack.config.test.mjs" "webpack.config.test.ts" "webpack.config.test.cts" "webpack.config.test.mts" "webpack.config.vendor.js" "webpack.config.vendor.cjs" "webpack.config.vendor.mjs" "webpack.config.vendor.ts" "webpack.config.vendor.cts" "webpack.config.vendor.mts" "webpack.config.vendor.production.js" "webpack.config.vendor.production.cjs" "webpack.config.vendor.production.mjs" "webpack.config.vendor.production.ts" "webpack.config.vendor.production.cts" "webpack.config.vendor.production.mts" "webpack.test.js" "webpack.test.cjs" "webpack.test.mjs" "webpack.test.ts" "webpack.test.cts" "webpack.test.mts" "webpack.dist.js" "webpack.dist.cjs" "webpack.dist.mjs" "webpack.dist.ts" "webpack.dist.cts" "webpack.dist.mts" "webpackfile.js" "webpackfile.cjs" "webpackfile.mjs" "webpackfile.ts" "webpackfile.cts" "webpackfile.mts"))
    (treemacs-create-icon :file "ionic.svg"              :extensions ("ionic.config.json" ".io-config.json"))
    (treemacs-create-icon :file "gulp.svg"               :extensions ("gulpfile.js" "gulpfile.mjs" "gulpfile.ts" "gulpfile.cts" "gulpfile.mts" "gulpfile.babel.js"))
    (treemacs-create-icon :file "nodejs.svg"             :extensions ("package.json" "package-lock.json" ".nvmrc" ".esmrc" ".node-version"))
    (treemacs-create-icon :file "npm.svg"                :extensions (".npmignore" ".npmrc"))
    (treemacs-create-icon :file "yarn.svg"               :extensions (".yarnrc" "yarn.lock" ".yarnclean" ".yarn-integrity" "yarn-error.log" ".yarnrc.yml" ".yarnrc.yaml"))
    (treemacs-create-icon :file "android.svg"            :extensions ("apk" "smali" "dex" "androidmanifest.xml"))
    (treemacs-create-icon :file "tune.svg"               :extensions ("env" ".env.defaults" ".env.example" ".env.sample" ".env.template" ".env.schema" ".env.local" ".env.dev" ".env.development" ".env.alpha" ".env.e2e" ".env.qa" ".env.dist" ".env.prod" ".env.production" ".env.stage" ".env.staging" ".env.preview" ".env.test" ".env.testing" ".env.development.local" ".env.qa.local" ".env.production.local" ".env.staging.local" ".env.test.local" ".env.uat"))
    (treemacs-create-icon :file "turborepo.svg"          :extensions ("turbo.json"))
    (treemacs-create-icon :file "babel.svg"              :extensions (".babelrc" ".babelrc.cjs" ".babelrc.js" ".babelrc.mjs" ".babelrc.json" "babel.config.cjs" "babel.config.js" "babel.config.mjs" "babel.config.json" "babel-transform.js" ".babel-plugin-macrosrc" ".babel-plugin-macrosrc.json" ".babel-plugin-macrosrc.yaml" ".babel-plugin-macrosrc.yml" ".babel-plugin-macrosrc.js" "babel-plugin-macros.config.js"))
    (treemacs-create-icon :file "blitz.svg"              :extensions ("blitz.config.js" "blitz.config.ts" ".blitz.config.compiled.js"))
    (treemacs-create-icon :file "contributing.svg"       :extensions ("contributing.md" "contributing.rst" "contributing.txt" "contributing"))
    (treemacs-create-icon :file "readme.svg"             :extensions ("readme.md" "readme.rst" "readme.txt" "readme"))
    (treemacs-create-icon :file "changelog.svg"          :extensions ("changelog" "changelog.md" "changelog.rst" "changelog.txt" "changes" "changes.md" "changes.rst" "changes.txt"))
    (treemacs-create-icon :file "architecture.svg"       :extensions ("architecture.md" "architecture.rst" "architecture.txt" "architecture"))
    (treemacs-create-icon :file "credits.svg"            :extensions ("credits.md" "credits.rst" "credits.txt" "credits"))
    (treemacs-create-icon :file "authors.svg"            :extensions ("authors.md" "authors.rst" "authors.txt" "authors" "contributors.md" "contributors.rst" "contributors.txt" "contributors"))
    (treemacs-create-icon :file "flow.svg"               :extensions (".flowconfig"))
    (treemacs-create-icon :file "favicon.svg"            :extensions ("favicon.ico"))
    (treemacs-create-icon :file "karma.svg"              :extensions ("karma.conf.js" "karma.conf.ts" "karma.conf.coffee" "karma.config.js" "karma.config.ts" "karma-main.js" "karma-main.ts"))
    (treemacs-create-icon :file "bithound.svg"           :extensions (".bithoundrc"))
    (treemacs-create-icon :file "svgo.svg"               :extensions ("svgo.config.js" "svgo.config.cjs" "svgo.config.mjs"))
    (treemacs-create-icon :file "appveyor.svg"           :extensions (".appveyor.yml" "appveyor.yml"))
    (treemacs-create-icon :file "travis.svg"             :extensions (".travis.yml"))
    (treemacs-create-icon :file "codecov.svg"            :extensions (".codecov.yml" "codecov.yml"))
    (treemacs-create-icon :file "sonarcloud.svg"         :extensions ("sonar-project.properties" ".sonarcloud.properties" "sonarcloud.yaml"))
    (treemacs-create-icon :file "protractor.svg"         :extensions ("protractor.conf.js" "protractor.conf.ts" "protractor.conf.coffee" "protractor.config.js" "protractor.config.ts"))
    (treemacs-create-icon :file "fusebox.svg"            :extensions ("fuse.js"))
    (treemacs-create-icon :file "heroku.svg"             :extensions ("procfile" "procfile.windows"))
    (treemacs-create-icon :file "editorconfig.svg"       :extensions (".editorconfig"))
    (treemacs-create-icon :file "gitlab.svg"             :extensions ("gitlab-ci.yml"))
    (treemacs-create-icon :file "bower.svg"              :extensions (".bowerrc" "bower.json"))
    (treemacs-create-icon :file "eslint.svg"             :extensions (".eslintrc.js" ".eslintrc.cjs" ".eslintrc.yaml" ".eslintrc.yml" ".eslintrc.json" ".eslintrc-md.js" ".eslintrc-jsdoc.js" ".eslintrc" ".eslintignore" ".eslintcache" "eslint.config.js"))
    (treemacs-create-icon :file "conduct.svg"            :extensions ("code_of_conduct.md" "code_of_conduct.txt" "code_of_conduct"))
    (treemacs-create-icon :file "watchman.svg"           :extensions (".watchmanconfig"))
    (treemacs-create-icon :file "aurelia.svg"            :extensions ("aurelia.json"))
    (treemacs-create-icon :file "auto.svg"               :extensions (".autorc" "auto.config.js" "auto.config.ts" "auto-config.json" "auto-config.yaml" "auto-config.yml" "auto-config.ts" "auto-config.js"))
    (treemacs-create-icon :file "mocha.svg"              :extensions ("mocha.opts" ".mocharc.yml" ".mocharc.yaml" ".mocharc.js" ".mocharc.json" ".mocharc.jsonc"))
    (treemacs-create-icon :file "jenkins.svg"            :extensions ("jenkinsfile" "jenkins" "jenkinsfile"))
    (treemacs-create-icon :file "firebase.svg"           :extensions ("firebase.json" ".firebaserc" "firestore.rules" "firestore.indexes.json"))
    (treemacs-create-icon :file "figma.svg"              :extensions ("fig"))
    (treemacs-create-icon :file "rollup.svg"             :extensions ("rollup.config.js" "rollup.config.mjs" "rollup.config.ts" "rollup-config.js" "rollup-config.mjs" "rollup-config.ts" "rollup.config.common.js" "rollup.config.common.mjs" "rollup.config.common.ts" "rollup.config.base.js" "rollup.config.base.mjs" "rollup.config.base.ts" "rollup.config.prod.js" "rollup.config.prod.mjs" "rollup.config.prod.ts" "rollup.config.dev.js" "rollup.config.dev.mjs" "rollup.config.dev.ts" "rollup.config.prod.vendor.js" "rollup.config.prod.vendor.mjs" "rollup.config.prod.vendor.ts"))
    (treemacs-create-icon :file "hack.svg"               :extensions (".hhconfig"))
    (treemacs-create-icon :file "hardhat.svg"            :extensions ("hardhat.config.js" "hardhat.config.ts"))
    (treemacs-create-icon :file "stylelint.svg"          :extensions (".stylelintrc" "stylelint.config.js" "stylelint.config.cjs" ".stylelintrc.json" ".stylelintrc.yaml" ".stylelintrc.yml" ".stylelintrc.js" ".stylelintrc.cjs" ".stylelintignore" ".stylelintcache"))
    (treemacs-create-icon :file "code-climate.svg"       :extensions (".codeclimate.yml"))
    (treemacs-create-icon :file "prettier.svg"           :extensions (".prettierrc" "prettier.config.js" "prettier.config.cjs" ".prettierrc.js" ".prettierrc.cjs" ".prettierrc.json" ".prettierrc.json5" ".prettierrc.yaml" ".prettierrc.yml" ".prettierignore" ".prettierrc.toml"))
    (treemacs-create-icon :file "renovate.svg"           :extensions (".renovaterc" ".renovaterc.json" "renovate-config.json" "renovate.json" "renovate.json5"))
    (treemacs-create-icon :file "apollo.svg"             :extensions ("apollo.config.js"))
    (treemacs-create-icon :file "nodemon.svg"            :extensions ("nodemon.json" "nodemon-debug.json"))
    (treemacs-create-icon :file "ngrx-reducer.svg"       :extensions ("reducer.ts" "rootReducer.ts"))
    (treemacs-create-icon :file "ngrx-state.svg"         :extensions ("state.ts"))
    (treemacs-create-icon :file "ngrx-actions.svg"       :extensions ("actions.ts"))
    (treemacs-create-icon :file "ngrx-effects.svg"       :extensions ("effects.ts"))
    (treemacs-create-icon :file "ngrx-entity.svg"        :extensions (".entity"))
    (treemacs-create-icon :file "ngrx-selectors.svg"     :extensions ("selectors.ts"))
    (treemacs-create-icon :file "webhint.svg"            :extensions (".hintrc"))
    (treemacs-create-icon :file "browserlist.svg"        :extensions ("browserslist" ".browserslistrc"))
    (treemacs-create-icon :file "crystal.svg"            :extensions ("cr" "ecr"))
    (treemacs-create-icon :file "snyk.svg"               :extensions (".snyk"))
    (treemacs-create-icon :file "drone.svg"              :extensions ("drone.yml" ".drone.yml"))
    (treemacs-create-icon :file "cuda.svg"               :extensions ("cu" "cuh"))
    (treemacs-create-icon :file "log.svg"                :extensions ("log"))
    (treemacs-create-icon :file "dotjs.svg"              :extensions ("def" "dot" "jst"))
    (treemacs-create-icon :file "ejs.svg"                :extensions ("ejs"))
    (treemacs-create-icon :file "sequelize.svg"          :extensions (".sequelizerc"))
    (treemacs-create-icon :file "gatsby.svg"             :extensions ("gatsby-config.js" "gatsby-config.mjs" "gatsby-config.ts" "gatsby-node.js" "gatsby-node.mjs" "gatsby-node.ts" "gatsby-browser.js" "gatsby-browser.tsx" "gatsby-ssr.js" "gatsby-ssr.tsx"))
    (treemacs-create-icon :file "wakatime.svg"           :extensions (".wakatime-project" ".wakatime-project"))
    (treemacs-create-icon :file "circleci.svg"           :extensions ("circle.yml"))
    (treemacs-create-icon :file "cloudfoundry.svg"       :extensions (".cfignore"))
    (treemacs-create-icon :file "grunt.svg"              :extensions ("gruntfile.js" "gruntfile.ts" "gruntfile.coffee" "gruntfile.babel.js" "gruntfile.babel.ts" "gruntfile.babel.coffee"))
    (treemacs-create-icon :file "jest.svg"               :extensions ("jest.config.js" "jest.config.cjs" "jest.config.mjs" "jest.config.ts" "jest.config.cts" "jest.config.mts" "jest.config.json" "jest.e2e.config.js" "jest.e2e.config.cjs" "jest.e2e.config.mjs" "jest.e2e.config.ts" "jest.e2e.config.cts" "jest.e2e.config.mts" "jest.e2e.config.json" "jest.e2e.json" "jest-unit.config.js" "jest-e2e.config.js" "jest-e2e.config.cjs" "jest-e2e.config.mjs" "jest-e2e.config.ts" "jest-e2e.config.cts" "jest-e2e.config.mts" "jest-e2e.config.json" "jest-e2e.json" "jest-github-actions-reporter.js" "jest.setup.js" "jest.setup.ts" "jest.json" ".jestrc" ".jestrc.js" ".jestrc.json" "jest.teardown.js"))
    (treemacs-create-icon :file "processing.svg"         :extensions ("pde"))
    (treemacs-create-icon :file "storybook.svg"          :extensions ("stories.js" "stories.jsx" "stories.mdx" "story.js" "story.jsx" "stories.ts" "stories.tsx" "story.ts" "story.tsx" "stories.svelte" "story.mdx"))
    (treemacs-create-icon :file "wepy.svg"               :extensions ("wpy"))
    (treemacs-create-icon :file "fastlane.svg"           :extensions ("fastfile" "appfile"))
    (treemacs-create-icon :file "hcl.svg"                :extensions ("hcl"))
    (treemacs-create-icon :file "helm.svg"               :extensions (".helmignore"))
    (treemacs-create-icon :file "san.svg"                :extensions ("san"))
    (treemacs-create-icon :file "wallaby.svg"            :extensions ("wallaby.js" "wallaby.conf.js"))
    (treemacs-create-icon :file "django.svg"             :extensions ("djt"))
    (treemacs-create-icon :file "stencil.svg"            :extensions ("stencil.config.js" "stencil.config.ts"))
    (treemacs-create-icon :file "red.svg"                :extensions ("red"))
    (treemacs-create-icon :file "makefile.svg"           :extensions ("mk" "makefile" "gnumakefile" "kbuild"))
    (treemacs-create-icon :file "foxpro.svg"             :extensions ("fxp" "prg"))
    (treemacs-create-icon :file "i18n.svg"               :extensions ("pot" "po" "mo" "lang"))
    (treemacs-create-icon :file "webassembly.svg"        :extensions ("wat" "wasm"))
    (treemacs-create-icon :file "semantic-release.svg"   :extensions (".releaserc" ".releaserc.yaml" ".releaserc.yml" ".releaserc.json" ".releaserc.js" "release.config.js"))
    (treemacs-create-icon :file "bitbucket.svg"          :extensions ("bitbucket-pipelines.yaml" "bitbucket-pipelines.yml"))
    (treemacs-create-icon :file "jupyter.svg"            :extensions ("ipynb"))
    (treemacs-create-icon :file "d.svg"                  :extensions ("d"))
    (treemacs-create-icon :file "mdx.svg"                :extensions ("mdx"))
    (treemacs-create-icon :file "mdsvex.svg"             :extensions ("svx"))
    (treemacs-create-icon :file "ballerina.svg"          :extensions ("bal" "balx"))
    (treemacs-create-icon :file "racket.svg"             :extensions ("rkt"))
    (treemacs-create-icon :file "bazel.svg"              :extensions ("bzl" "bazel" ".bazelignore" ".bazelrc" ".bazelversion"))
    (treemacs-create-icon :file "mint.svg"               :extensions ("mint"))
    (treemacs-create-icon :file "velocity.svg"           :extensions ("vm" "fhtml" "vtl"))
    (treemacs-create-icon :file "godot.svg"              :extensions ("gd"))
    (treemacs-create-icon :file "godot-assets.svg"       :extensions ("godot" "tres" "tscn" "gdns" "gdnlib" "gdshader" "gdextension"))
    (treemacs-create-icon :file "azure-pipelines.svg"    :extensions ("azure-pipelines.yml" "azure-pipelines.yaml" "azure-pipelines.yml" "azure-pipelines.yaml"))
    (treemacs-create-icon :file "azure.svg"              :extensions ("azcli"))
    (treemacs-create-icon :file "vagrant.svg"            :extensions ("vagrantfile" "vagrantfile"))
    (treemacs-create-icon :file "prisma.svg"             :extensions ("prisma" "prisma.yml"))
    (treemacs-create-icon :file "razor.svg"              :extensions ("cshtml" "vbhtml"))
    (treemacs-create-icon :file "abc.svg"                :extensions ("abc"))
    (treemacs-create-icon :file "asciidoc.svg"           :extensions ("ad" "adoc" "asciidoc"))
    (treemacs-create-icon :file "istanbul.svg"           :extensions (".nycrc" ".nycrc.json"))
    (treemacs-create-icon :file "edge.svg"               :extensions ("edge"))
    (treemacs-create-icon :file "scheme.svg"             :extensions ("ss" "scm"))
    (treemacs-create-icon :file "lisp.svg"               :extensions ("lisp" "lsp" "cl" "fast"))
    (treemacs-create-icon :file "tailwindcss.svg"        :extensions ("tailwind.js" "tailwind.ts" "tailwind.config.js" "tailwind.config.cjs" "tailwind.config.ts" "tailwind.config.cts"))
    (treemacs-create-icon :file "3d.svg"                 :extensions ("stl" "stp" "obj" "ac" "blend" "fbx" "mesh" "mqo" "pmd" "pmx" "skp" "vac" "vdp" "vox"))
    (treemacs-create-icon :file "buildkite.svg"          :extensions ("buildkite.yml" "buildkite.yaml"))
    (treemacs-create-icon :file "netlify.svg"            :extensions ("netlify.json" "netlify.yml" "netlify.yaml" "netlify.toml"))
    (treemacs-create-icon :file "svg.svg"                :extensions ("svg"))
    (treemacs-create-icon :file "svelte.svg"             :extensions ("svelte" "svelte.config.js" "svelte.config.cjs"))
    (treemacs-create-icon :file "vim.svg"                :extensions ("vimrc" "gvimrc" "exrc" "vim" "viminfo"))
    (treemacs-create-icon :file "nest.svg"               :extensions ("nest-cli.json" ".nest-cli.json" "nestconfig.json" ".nestconfig.json"))
    (treemacs-create-icon :file "nest-controller.svg"    :extensions ("controller.ts" "controller.js"))
    (treemacs-create-icon :file "nest-middleware.svg"    :extensions ("middleware.ts" "middleware.js"))
    (treemacs-create-icon :file "nest-module.svg"        :extensions ("module.ts" "module.js"))
    (treemacs-create-icon :file "nest-service.svg"       :extensions ("service.ts" "service.js"))
    (treemacs-create-icon :file "nest-decorator.svg"     :extensions ("decorator.ts" "decorator.js"))
    (treemacs-create-icon :file "nest-pipe.svg"          :extensions ("pipe.ts" "pipe.js"))
    (treemacs-create-icon :file "nest-filter.svg"        :extensions ("filter.ts" "filter.js"))
    (treemacs-create-icon :file "nest-gateway.svg"       :extensions ("gateway.ts" "gateway.js"))
    (treemacs-create-icon :file "nest-guard.svg"         :extensions ("guard.ts" "guard.js"))
    (treemacs-create-icon :file "nest-resolver.svg"      :extensions ("resolver.ts" "resolver.js"))
    (treemacs-create-icon :file "moonscript.svg"         :extensions ("moon"))
    (treemacs-create-icon :file "percy.svg"              :extensions (".percy.yml"))
    (treemacs-create-icon :file "gitpod.svg"             :extensions (".gitpod.yml"))
    (treemacs-create-icon :file "advpl_prw.svg"          :extensions ("prw" "prx"))
    (treemacs-create-icon :file "advpl_ptm.svg"          :extensions ("ptm"))
    (treemacs-create-icon :file "advpl_tlpp.svg"         :extensions ("tlpp"))
    (treemacs-create-icon :file "advpl_include.svg"      :extensions ("ch"))
    (treemacs-create-icon :file "codeowners.svg"         :extensions ("codeowners"))
    (treemacs-create-icon :file "gcp.svg"                :extensions (".gcloudignore"))
    (treemacs-create-icon :file "disc.svg"               :extensions ("iso"))
    (treemacs-create-icon :file "fortran.svg"            :extensions ("f" "f77" "f90" "f95" "f03" "f08"))
    (treemacs-create-icon :file "tcl.svg"                :extensions ("tcl"))
    (treemacs-create-icon :file "liquid.svg"             :extensions ("liquid"))
    (treemacs-create-icon :file "prolog.svg"             :extensions ("p" "pro" "pl"))
    (treemacs-create-icon :file "husky.svg"              :extensions (".huskyrc" "husky.config.js" ".huskyrc.json" ".huskyrc.js" ".huskyrc.yaml" ".huskyrc.yml"))
    (treemacs-create-icon :file "coconut.svg"            :extensions ("coco"))
    (treemacs-create-icon :file "tilt.svg"               :extensions ("tiltfile"))
    (treemacs-create-icon :file "capacitor.svg"          :extensions ("capacitor.config.json" "capacitor.config.ts"))
    (treemacs-create-icon :file "sketch.svg"             :extensions ("sketch"))
    (treemacs-create-icon :file "pawn.svg"               :extensions ("pwn" "amx"))
    (treemacs-create-icon :file "adonis.svg"             :extensions (".adonisrc.json" "ace"))
    (treemacs-create-icon :file "forth.svg"              :extensions ("4th" "fth" "frt"))
    (treemacs-create-icon :file "uml.svg"                :extensions ("iuml" "pu" "puml" "plantuml" "wsd"))
    (treemacs-create-icon :file "meson.svg"              :extensions ("wrap" "meson.build" "meson_options.txt"))
    (treemacs-create-icon :file "commitlint.svg"         :extensions (".commitlintrc" ".commitlintrc.js" ".commitlintrc.cjs" ".commitlintrc.ts" ".commitlintrc.cts" ".commitlintrc.json" ".commitlintrc.yaml" ".commitlintrc.yml" ".commitlint.yaml" ".commitlint.yml" "commitlint.config.js" "commitlint.config.cjs" "commitlint.config.ts" "commitlint.config.cts"))
    (treemacs-create-icon :file "buck.svg"               :extensions (".buckconfig"))
    (treemacs-create-icon :file "dhall.svg"              :extensions ("dhall" "dhallb"))
    (treemacs-create-icon :file "sml.svg"                :extensions ("sml" "mlton" "mlb" "sig" "fun" "cm" "lex" "use" "grm"))
    (treemacs-create-icon :file "nrwl.svg"               :extensions ("nx.json" ".nxignore"))
    (treemacs-create-icon :file "opam.svg"               :extensions ("opam"))
    (treemacs-create-icon :file "dune.svg"               :extensions ("dune" "dune-project" "dune-workspace" "dune-workspace.dev"))
    (treemacs-create-icon :file "imba.svg"               :extensions ("imba"))
    (treemacs-create-icon :file "drawio.svg"             :extensions ("drawio" "dio"))
    (treemacs-create-icon :file "pascal.svg"             :extensions ("pas"))
    (treemacs-create-icon :file "shaderlab.svg"          :extensions ("unity"))
    (treemacs-create-icon :file "roadmap.svg"            :extensions ("roadmap.md" "roadmap.txt" "timeline.md" "timeline.txt" "milestones.md" "milestones.txt"))
    (treemacs-create-icon :file "sas.svg"                :extensions ("sas" "sas7bdat" "sashdat" "astore" "ast" "sast"))
    (treemacs-create-icon :file "nuget.svg"              :extensions ("nupkg" "nuget.config" ".nuspec" "nuget.exe"))
    (treemacs-create-icon :file "command.svg"            :extensions ("command"))
    (treemacs-create-icon :file "stryker.svg"            :extensions ("stryker.conf.js" "stryker.conf.json"))
    (treemacs-create-icon :file "denizenscript.svg"      :extensions ("dsc"))
    (treemacs-create-icon :file "modernizr.svg"          :extensions (".modernizrrc" ".modernizrrc.js" ".modernizrrc.json"))
    (treemacs-create-icon :file "slug.svg"               :extensions (".slugignore"))
    (treemacs-create-icon :file "search.svg"             :extensions ("code-search"))
    (treemacs-create-icon :file "stitches.svg"           :extensions ("stitches.config.js" "stitches.config.ts"))
    (treemacs-create-icon :file "nginx.svg"              :extensions ("nginx" "nginxconfig" "nginx.conf"))
    (treemacs-create-icon :file "minecraft.svg"          :extensions ("mcfunction" "mcmeta" "mcr" "mca" "mcgame" "mclevel" "mcworld" "mine" "mus" "mcstructure" "mcpack" "mcaddon" ".mcattributes" ".mcdefinitions" ".mcignore"))
    (treemacs-create-icon :file "replit.svg"             :extensions (".replit"))
    (treemacs-create-icon :file "rescript.svg"           :extensions ("res"))
    (treemacs-create-icon :file "rescript-interface.svg" :extensions ("resi"))
    (treemacs-create-icon :file "snowpack.svg"           :extensions ("snowpack.config.js" "snowpack.config.cjs" "snowpack.config.mjs" "snowpack.config.ts" "snowpack.config.cts" "snowpack.config.mts" "snowpack.deps.json" "snowpack.config.json"))
    (treemacs-create-icon :file "brainfuck.svg"          :extensions ("b" "bf"))
    (treemacs-create-icon :file "bicep.svg"              :extensions ("bicep"))
    (treemacs-create-icon :file "cobol.svg"              :extensions ("cob" "cbl"))
    (treemacs-create-icon :file "grain.svg"              :extensions ("gr"))
    (treemacs-create-icon :file "lolcode.svg"            :extensions ("lol"))
    (treemacs-create-icon :file "idris.svg"              :extensions ("idr" "ibc"))
    (treemacs-create-icon :file "quasar.svg"             :extensions ("quasar.conf.js" "quasar.config.js"))
    (treemacs-create-icon :file "dependabot.svg"         :extensions ("dependabot.yml" "dependabot.yaml"))
    (treemacs-create-icon :file "pipeline.svg"           :extensions ("pipeline"))
    (treemacs-create-icon :file "vite.svg"               :extensions ("vite.config.js" "vite.config.mjs" "vite.config.cjs" "vite.config.ts" "vite.config.cts" "vite.config.mts"))
    (treemacs-create-icon :file "vitest.svg"             :extensions ("vitest.config.ts" "vitest.config.mts" "vitest.config.cts" "vitest.config.js" "vitest.config.mjs" "vitest.config.cjs"))
    (treemacs-create-icon :file "opa.svg"                :extensions ("rego"))
    (treemacs-create-icon :file "lerna.svg"              :extensions ("lerna.json"))
    (treemacs-create-icon :file "windicss.svg"           :extensions ("windi" "windi.config.js" "windi.config.cjs" "windi.config.ts" "windi.config.cts" "windi.config.json"))
    (treemacs-create-icon :file "textlint.svg"           :extensions (".textlintrc"))
    (treemacs-create-icon :file "scala.svg"              :extensions ("scala" "sc"))
    (treemacs-create-icon :file "lilypond.svg"           :extensions ("ly"))
    (treemacs-create-icon :file "vlang.svg"              :extensions ("v" "vpkg.json" "v.mod"))
    (treemacs-create-icon :file "chess.svg"              :extensions ("pgn" "fen"))
    (treemacs-create-icon :file "gemini.svg"             :extensions ("gmi" "gemini"))
    (treemacs-create-icon :file "sentry.svg"             :extensions (".sentryclirc"))
    (treemacs-create-icon :file "phpunit.svg"            :extensions (".phpunit.result.cache" ".phpunit-watcher.yml" "phpunit.xml" "phpunit.xml.dist" "phpunit-watcher.yml" "phpunit-watcher.yml.dist"))
    (treemacs-create-icon :file "php-cs-fixer.svg"       :extensions (".php_cs" ".php_cs.dist" ".php_cs.php" ".php_cs.dist.php" ".php-cs-fixer.php" ".php-cs-fixer.dist.php"))
    (treemacs-create-icon :file "robots.svg"             :extensions ("robots.txt"))
    (treemacs-create-icon :file "tsconfig.svg"           :extensions ("tsconfig.json" "tsconfig.json" "tsconfig.app.json" "tsconfig.editor.json" "tsconfig.spec.json" "tsconfig.base.json" "tsconfig.build.json" "tsconfig.eslint.json" "tsconfig.lib.json" "tsconfig.lib.prod.json" "tsconfig.node.json" "tsconfig.test.json" "tsconfig.e2e.json" "tsconfig.web.json" "tsconfig.webworker.json" "tsconfig.worker.json" "tsconfig.config.json" "tsconfig.vitest.json" "tsconfig.cjs.json" "tsconfig.esm.json" "tsconfig.mjs.json" "tsconfig.doc.json"))
    (treemacs-create-icon :file "tauri.svg"              :extensions ("tauri" "tauri.conf.json" "tauri.config.json" "tauri.linux.conf.json" "tauri.windows.conf.json" "tauri.macos.conf.json"))
    (treemacs-create-icon :file "jsconfig.svg"           :extensions ("jsconfig.json" "jsconfig.json"))
    (treemacs-create-icon :file "maven.svg"              :extensions ("maven.config" "jvm.config" "pom.xml"))
    (treemacs-create-icon :file "ada.svg"                :extensions ("ada" "adb" "ads" "ali"))
    (treemacs-create-icon :file "serverless.svg"         :extensions ("serverless.yml"))
    (treemacs-create-icon :file "supabase.svg"           :extensions ("supabase.js" "supabase.py"))
    (treemacs-create-icon :file "ember.svg"              :extensions (".ember-cli" ".ember-cli.js" "ember-cli-builds.js"))
    (treemacs-create-icon :file "horusec.svg"            :extensions ("horusec-config.json" "horusec-config.json"))
    (treemacs-create-icon :file "poetry.svg"             :extensions ("poetry.lock"))
    (treemacs-create-icon :file "coala.svg"              :extensions ("coarc" "coafile"))
    (treemacs-create-icon :file "parcel.svg"             :extensions (".parcelrc"))
    (treemacs-create-icon :file "dinophp.svg"            :extensions ("bubble" "html.bubble" "php.bubble"))
    (treemacs-create-icon :file "teal.svg"               :extensions ("tl"))
    (treemacs-create-icon :file "template.svg"           :extensions ("template"))
    (treemacs-create-icon :file "astyle.svg"             :extensions (".astylerc"))
    (treemacs-create-icon :file "shader.svg"             :extensions ("glsl" "vert" "tesc" "tese" "geom" "frag" "comp" "vert.glsl" "tesc.glsl" "tese.glsl" "geom.glsl" "frag.glsl" "comp.glsl" "vertex.glsl" "geometry.glsl" "fragment.glsl" "compute.glsl" "ts.glsl" "gs.glsl" "vs.glsl" "fs.glsl" "shader" "vertexshader" "fragmentshader" "geometryshader" "computeshader" "hlsl" "pixel.hlsl" "geometry.hlsl" "compute.hlsl" "tessellation.hlsl" "px.hlsl" "geom.hlsl" "comp.hlsl" "tess.hlsl" "wgsl"))
    (treemacs-create-icon :file "lighthouse.svg"         :extensions (".lighthouserc.js" "lighthouserc.js" ".lighthouserc.json" "lighthouserc.json" ".lighthouserc.yml" "lighthouserc.yml" ".lighthouserc.yaml" "lighthouserc.yaml"))
    (treemacs-create-icon :file "svgr.svg"               :extensions (".svgrrc" "svgr.config.js" ".svgrrc.js" ".svgrrc.yaml" ".svgrrc.yml" ".svgrrc.json"))
    (treemacs-create-icon :file "rome.svg"               :extensions ("rome.json"))
    (treemacs-create-icon :file "cypress.svg"            :extensions ("cypress.json" "cypress.env.json" "cypress.config.ts" "cypress.config.js" "cypress.config.cjs" "cypress.config.mjs"))
    (treemacs-create-icon :file "siyuan.svg"             :extensions ("sy"))
    (treemacs-create-icon :file "ndst.svg"               :extensions ("ndst.yml" "ndst.yaml" "ndst.json"))
    (treemacs-create-icon :file "plop.svg"               :extensions ("plopfile.js" "plopfile.cjs" "plopfile.mjs" "plopfile.ts"))
    (treemacs-create-icon :file "tobi.svg"               :extensions ("tobi"))
    (treemacs-create-icon :file "tobimake.svg"           :extensions (".tobimake"))
    (treemacs-create-icon :file "gleam.svg"              :extensions ("gleam" "gleam.toml"))
    (treemacs-create-icon :file "pnpm.svg"               :extensions ("pnpm-lock.yaml" "pnpm-workspace.yaml" ".pnpmfile.cjs"))
    (treemacs-create-icon :file "gridsome.svg"           :extensions ("gridsome.config.js" "gridsome.server.js"))
    (treemacs-create-icon :file "steadybit.svg"          :extensions ("steadybit.yml" "steadybit.yaml" ".steadybit.yml" "steadybit.yml" ".steadybit.yaml" "steadybit.yaml"))
    (treemacs-create-icon :file "tree.svg"               :extensions ("tree"))
    (treemacs-create-icon :file "cadence.svg"            :extensions ("cdc"))
    (treemacs-create-icon :file "caddy.svg"              :extensions ("Caddyfile"))
    (treemacs-create-icon :file "bun.svg"                :extensions ("bun.lockb"))
    (treemacs-create-icon :file "antlr.svg"              :extensions ("g4"))
    (treemacs-create-icon :file "stylable.svg"           :extensions ("st.css"))
    (treemacs-create-icon :file "pinejs.svg"             :extensions ("pine"))
    (treemacs-create-icon :file "nano-staged.svg"        :extensions (".nano-staged.js" "nano-staged.js" ".nano-staged.cjs" "nano-staged.cjs" ".nano-staged.mjs" "nano-staged.mjs" ".nano-staged.json" "nano-staged.json" ".nanostagedrc"))
    (treemacs-create-icon :file "craco.svg"              :extensions ("craco.config.ts" "craco.config.js" "craco.config.cjs" ".cracorc.ts" ".cracorc.js" ".cracorc"))
    (treemacs-create-icon :file "gamemaker.svg"          :extensions ("gml" "yy" "yyp" "yyz"))
    (treemacs-create-icon :file "tldraw.svg"             :extensions ("tldr"))))

  (treemacs-load-theme "material-icons"))

(provide 'treemacs-material-icons)
;;; treemacs-material-icons.el ends here
